---
kind: pipeline
name: test

steps:
- name: cargo-build-test
  image: rust:alpine
  commands:
  - apk add musl-dev binutils
  - rustup target add x86_64-unknown-linux-musl
  - cargo build --all
  - cargo test --all
