---
kind: pipeline
name: build-and-test

steps:
- name: build-builder
  image: docker
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - docker build --target builder -t greetings-builder:latest .

- name: test
  image: greetings-builder:latest
  pull: if-not-exists
  commands:
  - just -f Justfile.docker test-release

- name: build-app
  image: docker
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - docker build -t greetings-app:latest .


volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock