---  # BUILD
kind: pipeline
name: build

steps:
- name: build-builder
  image: docker
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - docker build --target builder -t greetings-builder:latest .

- name: build-app
  image: docker
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - docker build -t greetings-app:latest .


volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock

---  # TEST
kind: pipeline
name: test

clone:
  disable: true

steps:
- name: test
  image: greetings-builder:latest
  pull: if-not-exists
  commands:
  - just test-release

depends_on:
- build
